/**
 * This data contain swiggy cards api data just can't update the images as image links are not used,
 * no access to swiggy database.
 *
 * but we can use by adding :
 * https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ + cloudinaryImageId
 *
 */

const data = {
    restaurants: [
        {
            info: {
                id: "44614",
                name: "Harishankar Veg Restro",
                cloudinaryImageId: "bhrvsquves5iopgp38bd",
                locality: "Vyas Marg",
                areaName: "Raja Park",
                costForTwo: "₹200 for two",
                cuisines: [
                    "North Indian",
                    "South Indian",
                    "Chinese",
                    "Italian",
                    "Continental",
                    "Pizzas",
                    "Chaat",
                    "Thalis",
                    "Jain",
                    "Snacks",
                    "Desserts",
                    "Fast Food",
                ],
                avgRating: 4.3,
                veg: true,
                parentId: "4864",
                avgRatingString: "4.3",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 18,
                    lastMileTravel: 0.3,
                    serviceability: "SERVICEABLE",
                    slaString: "18 mins",
                    lastMileTravelString: "0.3 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-04 00:00:00",
                    opened: true,
                },
                badges: {
                    imageBadges: [
                        {
                            imageId: "v1695133679/badges/Pure_Veg111.png",
                            description: "pureveg",
                        },
                    ],
                },
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {
                            badgeObject: [
                                {
                                    attributes: {
                                        description: "pureveg",
                                        imageId: "v1695133679/badges/Pure_Veg111.png",
                                    },
                                },
                            ],
                        },
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹249",
                    discountTag: "FLAT DEAL",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/harishankar-veg-restro-vyas-marg-raja-park-jaipur-44614",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "216674",
                name: "Burger King",
                cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
                locality: "Pink Square Mall",
                areaName: "Adarsh Nagar",
                costForTwo: "₹350 for two",
                cuisines: ["Burgers", "American"],
                avgRating: 4.3,
                parentId: "166",
                avgRatingString: "4.3",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 25,
                    lastMileTravel: 1.2,
                    serviceability: "SERVICEABLE",
                    slaString: "25 mins",
                    lastMileTravelString: "1.2 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-04 02:00:00",
                    opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {},
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "ITEMS",
                    subHeader: "AT ₹129",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/burger-king-pink-square-mall-adarsh-nagar-jaipur-216674",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "44359",
                name: "Sethi Bar-Be-Que",
                cloudinaryImageId: "ypcc8quio98rj9xxwekh",
                locality: "Raja Park",
                areaName: "Raja Park",
                costForTwo: "₹300 for two",
                cuisines: [
                    "North Indian",
                    "Mughlai",
                    "Chinese",
                    "Biryani",
                    "Afghani",
                    "Kebabs",
                    "Punjabi",
                ],
                avgRating: 4.3,
                parentId: "180073",
                avgRatingString: "4.3",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 21,
                    lastMileTravel: 0.1,
                    serviceability: "SERVICEABLE",
                    slaString: "21 mins",
                    lastMileTravelString: "0.1 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-04 02:00:00",
                    opened: true,
                },
                badges: {},
                select: true,
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {},
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹249",
                    discountTag: "FLAT DEAL",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/sethi-bar-be-que-raja-park-jaipur-44359",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "47596",
                name: "Pizza Hut",
                cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
                locality: "Tilak Nagar",
                areaName: "Raja Park",
                costForTwo: "₹350 for two",
                cuisines: ["Pizzas"],
                avgRating: 4,
                parentId: "721",
                avgRatingString: "4.0",
                totalRatingsString: "5K+",
                sla: {
                    deliveryTime: 25,
                    lastMileTravel: 0.8,
                    serviceability: "SERVICEABLE",
                    slaString: "25 mins",
                    lastMileTravelString: "0.8 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-04 04:00:00",
                    opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {},
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "50% OFF",
                    subHeader: "UPTO ₹100",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/pizza-hut-tilak-nagar-raja-park-jaipur-47596",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "107916",
                name: "Rominus Pizza & Burger",
                cloudinaryImageId: "9ec9ffd900c24ef751e2f34ba3d2fd4b",
                locality: "Tilak Nagar",
                areaName: "Raja Park",
                costForTwo: "₹200 for two",
                cuisines: [
                    "Pizzas",
                    "Italian-American",
                    "American",
                    "Barbecue",
                    "Snacks",
                    "Italian",
                    "Pastas",
                    "Grill",
                    "Sweets",
                    "Desserts",
                    "Beverages",
                ],
                avgRating: 4.3,
                parentId: "8387",
                avgRatingString: "4.3",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 28,
                    lastMileTravel: 0.8,
                    serviceability: "SERVICEABLE",
                    slaString: "28 mins",
                    lastMileTravelString: "0.8 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-04 04:00:00",
                    opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {},
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "50% OFF",
                    subHeader: "UPTO ₹100",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/rominus-pizza-and-burger-tilak-nagar-raja-park-jaipur-107916",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "453638",
                name: "Sushiya",
                cloudinaryImageId: "0fedc164f23a5439b7bdeb1feb64759f",
                locality: "Raja Park",
                areaName: "Raja Park",
                costForTwo: "₹800 for two",
                cuisines: ["Japanese", "Asian"],
                avgRating: 4.3,
                parentId: "908",
                avgRatingString: "4.3",
                totalRatingsString: "100+",
                sla: {
                    deliveryTime: 27,
                    lastMileTravel: 0.1,
                    serviceability: "SERVICEABLE",
                    slaString: "27 mins",
                    lastMileTravelString: "0.1 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-03 23:00:00",
                    opened: true,
                },
                badges: {
                    imageBadges: [
                        {
                            imageId: "newg.png",
                            description: "Gourmet",
                        },
                    ],
                },
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {
                            badgeObject: [
                                {
                                    attributes: {
                                        description: "Gourmet",
                                        imageId: "newg.png",
                                    },
                                },
                            ],
                        },
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "60% OFF",
                    subHeader: "UPTO ₹120",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/sushiya-raja-park-jaipur-453638",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "47615",
                name: "Subway",
                cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
                locality: "Raja Park",
                areaName: "Raja Park",
                costForTwo: "₹200 for two",
                cuisines: [
                    "Fast Food",
                    "Healthy Food",
                    "Salads",
                    "Desserts",
                    "Beverages",
                    "Snacks",
                    "Continental",
                    "Italian",
                    "Italian-American",
                    "American",
                ],
                avgRating: 4.2,
                parentId: "2",
                avgRatingString: "4.2",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 20,
                    lastMileTravel: 0.3,
                    serviceability: "SERVICEABLE",
                    slaString: "20 mins",
                    lastMileTravelString: "0.3 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-03 23:30:00",
                    opened: true,
                },
                badges: {},
                isOpen: true,
                aggregatedDiscountInfoV2: {},
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {},
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/subway-raja-park-jaipur-47615",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "56417",
                name: "Tea Connect",
                cloudinaryImageId: "aqsuffxuk5eybguyxfss",
                locality: "Panchwati Circle",
                areaName: "Raja Park",
                costForTwo: "₹200 for two",
                cuisines: ["Snacks"],
                avgRating: 3.7,
                veg: true,
                parentId: "202665",
                avgRatingString: "3.7",
                totalRatingsString: "1K+",
                sla: {
                    deliveryTime: 24,
                    lastMileTravel: 0.1,
                    serviceability: "SERVICEABLE",
                    slaString: "24 mins",
                    lastMileTravelString: "0.1 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-03 23:59:00",
                    opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {},
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹249",
                    discountTag: "FLAT DEAL",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/tea-connect-panchwati-circle-raja-park-jaipur-56417",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "45989",
                name: "Marky Momos- Raja Park",
                cloudinaryImageId: "vnywgfhmaycozix5u7qh",
                areaName: "Raja Park",
                costForTwo: "₹200 for two",
                cuisines: [
                    "Chinese",
                    "Asian",
                    "Pan-Asian",
                    "Indian",
                    "Thai",
                    "Thalis",
                    "Kebabs",
                    "Grill",
                    "Tandoor",
                    "Biryani",
                    "Desserts",
                ],
                avgRating: 4.4,
                parentId: "4659",
                avgRatingString: "4.4",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 22,
                    lastMileTravel: 0.5,
                    serviceability: "SERVICEABLE",
                    slaString: "22 mins",
                    lastMileTravelString: "0.5 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-04 01:45:00",
                    opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {},
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "60% OFF",
                    discountTag: "FLAT DEAL",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/marky-momos-raja-park-raja-park-jaipur-45989",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "44889",
                name: "Kebabs & Curries Company",
                cloudinaryImageId: "yz7emjjjgximxrjpdtjj",
                locality: "Raja Park",
                areaName: "Raja Park",
                costForTwo: "₹700 for two",
                cuisines: [
                    "Indian",
                    "North Indian",
                    "Thalis",
                    "Chinese",
                    "Mughlai",
                    "Chaat",
                    "Punjabi",
                    "Desserts",
                    "Snacks",
                    "Rajasthani",
                    "Tandoor",
                    "Sweets",
                    "Beverages",
                    "Ice Cream",
                    "Italian",
                    "Pastas",
                ],
                avgRating: 4.2,
                parentId: "6302",
                avgRatingString: "4.2",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 23,
                    lastMileTravel: 0.4,
                    serviceability: "SERVICEABLE",
                    slaString: "23 mins",
                    lastMileTravelString: "0.4 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-03 23:59:00",
                    opened: true,
                },
                badges: {
                    imageBadges: [
                        {
                            imageId: "newg.png",
                            description: "Gourmet",
                        },
                    ],
                },
                isOpen: true,
                aggregatedDiscountInfoV2: {},
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {
                            badgeObject: [
                                {
                                    attributes: {
                                        description: "Gourmet",
                                        imageId: "newg.png",
                                    },
                                },
                            ],
                        },
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/kebabs-and-curries-company-raja-park-jaipur-44889",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "45968",
                name: "Baskin Robbins - Ice Cream Desserts",
                cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
                locality: "Dhruv Marg",
                areaName: "Raja Park",
                costForTwo: "₹300 for two",
                cuisines: ["Ice Cream", "Desserts"],
                avgRating: 4.2,
                veg: true,
                parentId: "5588",
                avgRatingString: "4.2",
                totalRatingsString: "1K+",
                sla: {
                    deliveryTime: 17,
                    lastMileTravel: 0.9,
                    serviceability: "SERVICEABLE",
                    slaString: "17 mins",
                    lastMileTravelString: "0.9 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-03 23:00:00",
                    opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {},
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "10% OFF",
                    subHeader: "ABOVE ₹1000",
                    discountTag: "FLAT DEAL",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/baskin-robbins-ice-cream-desserts-dhruv-marg-raja-park-jaipur-45968",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "73781",
                name: "Bombay Mishthan Bhandar (BMB) - Sanganeeri Gate",
                cloudinaryImageId: "127d6d2a1a4f3e995fba2c5dd93b574f",
                locality: "C Scheme",
                areaName: "MI Road",
                costForTwo: "₹300 for two",
                cuisines: [
                    "North Indian",
                    "Thalis",
                    "Chinese",
                    "Mughlai",
                    "Chaat",
                    "Punjabi",
                    "Desserts",
                    "Snacks",
                    "Rajasthani",
                    "Tandoor",
                    "Sweets",
                    "Indian",
                    "Beverages",
                    "Ice Cream",
                    "Italian",
                    "Pastas",
                ],
                avgRating: 4.4,
                veg: true,
                parentId: "13662",
                avgRatingString: "4.4",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 30,
                    lastMileTravel: 3,
                    serviceability: "SERVICEABLE",
                    slaString: "30 mins",
                    lastMileTravelString: "3.0 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-03 23:00:00",
                    opened: true,
                },
                badges: {
                    imageBadges: [
                        {
                            imageId: "v1695133679/badges/Pure_Veg111.png",
                            description: "pureveg",
                        },
                    ],
                },
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {
                            badgeObject: [
                                {
                                    attributes: {
                                        description: "pureveg",
                                        imageId: "v1695133679/badges/Pure_Veg111.png",
                                    },
                                },
                            ],
                        },
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹249",
                    discountTag: "FLAT DEAL",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/bombay-mishthan-bhandar-bmb-sanganeeri-gate-c-scheme-mi-road-jaipur-73781",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "137500",
                name: "Domino's Pizza",
                cloudinaryImageId: "ntqaphalrudmv27nozhu",
                locality: "Ramada Govind Marg",
                areaName: "Raja Park",
                costForTwo: "₹400 for two",
                cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
                avgRating: 4.2,
                parentId: "2456",
                avgRatingString: "4.2",
                totalRatingsString: "5K+",
                sla: {
                    deliveryTime: 25,
                    serviceability: "SERVICEABLE",
                    slaString: "25 mins",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-04 01:55:00",
                    opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {},
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "₹150 OFF",
                    subHeader: "ABOVE ₹299",
                    discountTag: "FLAT DEAL",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/dominos-pizza-ramada-govind-marg-raja-park-jaipur-137500",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "48348",
                name: "The Belgian Waffle Co.",
                cloudinaryImageId: "5116a385bac0548e06c33c08350fbf11",
                locality: "Subhash Marg",
                areaName: "C Scheme",
                costForTwo: "₹200 for two",
                cuisines: ["Waffle", "Desserts", "Ice Cream", "Beverages"],
                avgRating: 4.6,
                veg: true,
                parentId: "2233",
                avgRatingString: "4.6",
                totalRatingsString: "5K+",
                sla: {
                    deliveryTime: 28,
                    lastMileTravel: 3,
                    serviceability: "SERVICEABLE",
                    slaString: "28 mins",
                    lastMileTravelString: "3.0 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-04 00:00:00",
                    opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {},
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "20% OFF",
                    subHeader: "UPTO ₹50",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/the-belgian-waffle-co-subhash-marg-c-scheme-jaipur-48348",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "249749",
                name: "McDonald's",
                cloudinaryImageId: "6dc3ed2ca21d71acff7c2a51dfe4c720",
                locality: "Civil Lines",
                areaName: "Civil Lines",
                costForTwo: "₹400 for two",
                cuisines: ["American"],
                avgRating: 4.4,
                parentId: "630",
                avgRatingString: "4.4",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 27,
                    lastMileTravel: 4.5,
                    serviceability: "SERVICEABLE",
                    slaString: "27 mins",
                    lastMileTravelString: "4.5 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-04 00:50:00",
                    opened: true,
                },
                badges: {},
                isOpen: true,
                aggregatedDiscountInfoV2: {},
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {},
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/mcdonalds-civil-lines-jaipur-249749",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "50946",
                name: "The Tea Connect",
                cloudinaryImageId: "omsi7qfzvxvlf0pn4v46",
                locality: "Rambagh",
                areaName: "Bapu Nagar",
                costForTwo: "₹200 for two",
                cuisines: [
                    "Pizzas",
                    "Snacks",
                    "Chinese",
                    "Beverages",
                    "Italian-American",
                    "Continental",
                ],
                avgRating: 3.8,
                veg: true,
                parentId: "231122",
                avgRatingString: "3.8",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 30,
                    lastMileTravel: 3,
                    serviceability: "SERVICEABLE",
                    slaString: "30 mins",
                    lastMileTravelString: "3.0 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-04 03:45:00",
                    opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {},
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹249",
                    discountTag: "FLAT DEAL",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/the-tea-connect-rambagh-bapu-nagar-jaipur-50946",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "44439",
                name: "Kanha",
                cloudinaryImageId: "d0d837e45d962005a9b7504279649dd5",
                locality: "C Scheme",
                areaName: "C Scheme",
                costForTwo: "₹200 for two",
                cuisines: [
                    "Sweets",
                    "Fast Food",
                    "North Indian",
                    "South Indian",
                    "Chinese",
                    "Snacks",
                    "Beverages",
                    "Indian",
                    "Continental",
                    "Italian",
                    "American",
                    "Rajasthani",
                    "Chaat",
                    "Thalis",
                    "Bakery",
                    "Grill",
                    "Salads",
                    "Healthy Food",
                    "Pizzas",
                ],
                avgRating: 4.5,
                veg: true,
                parentId: "4650",
                avgRatingString: "4.5",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 28,
                    lastMileTravel: 4.4,
                    serviceability: "SERVICEABLE",
                    slaString: "28 mins",
                    lastMileTravelString: "4.4 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-03 22:45:00",
                    opened: true,
                },
                badges: {
                    imageBadges: [
                        {
                            imageId: "v1695133679/badges/Pure_Veg111.png",
                            description: "pureveg",
                        },
                    ],
                },
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {
                            badgeObject: [
                                {
                                    attributes: {
                                        description: "pureveg",
                                        imageId: "v1695133679/badges/Pure_Veg111.png",
                                    },
                                },
                            ],
                        },
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "50% OFF",
                    subHeader: "UPTO ₹100",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/kanha-c-scheme-jaipur-44439",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "72860",
                name: "Sodhani Sweets",
                cloudinaryImageId: "pjsaxa4bkfphmjeiatt6",
                locality: "Johari Bazaar",
                areaName: "Pink City",
                costForTwo: "₹300 for two",
                cuisines: ["Sweets", "Thalis", "Snacks", "Rajasthani", "Indian"],
                avgRating: 4.5,
                veg: true,
                parentId: "190628",
                avgRatingString: "4.5",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 34,
                    lastMileTravel: 3.8,
                    serviceability: "SERVICEABLE",
                    slaString: "34 mins",
                    lastMileTravelString: "3.8 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-03 21:30:00",
                    opened: true,
                },
                badges: {
                    imageBadges: [
                        {
                            imageId: "v1695133679/badges/Pure_Veg111.png",
                            description: "pureveg",
                        },
                    ],
                },
                isOpen: true,
                aggregatedDiscountInfoV2: {},
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {
                            badgeObject: [
                                {
                                    attributes: {
                                        description: "pureveg",
                                        imageId: "v1695133679/badges/Pure_Veg111.png",
                                    },
                                },
                            ],
                        },
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/sodhani-sweets-johari-bazaar-pink-city-jaipur-72860",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "46090",
                name: "DMB Sweets Pvt Ltd",
                cloudinaryImageId: "drarpnpeqchbx8yfwvlw",
                locality: "Lal Kothi",
                areaName: "Lal Kothi",
                costForTwo: "₹350 for two",
                cuisines: [
                    "Sweets",
                    "North Indian",
                    "Jain",
                    "South Indian",
                    "Snacks",
                    "Bengali",
                    "Italian",
                    "Desserts",
                ],
                avgRating: 4.5,
                parentId: "244910",
                avgRatingString: "4.5",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 24,
                    lastMileTravel: 4.6,
                    serviceability: "SERVICEABLE",
                    slaString: "24 mins",
                    lastMileTravelString: "4.6 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-03 22:00:00",
                    opened: true,
                },
                badges: {
                    imageBadges: [
                        {
                            imageId: "v1695133679/badges/Pure_Veg111.png",
                            description: "pureveg",
                        },
                    ],
                },
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {
                            badgeObject: [
                                {
                                    attributes: {
                                        description: "pureveg",
                                        imageId: "v1695133679/badges/Pure_Veg111.png",
                                    },
                                },
                            ],
                        },
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "50% OFF",
                    subHeader: "UPTO ₹100",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/dmb-sweets-pvt-ltd-lal-kothi-jaipur-46090",
                type: "WEBLINK",
            },
        },
        {
            info: {
                id: "45977",
                name: "Burger Farm",
                cloudinaryImageId: "nzcyy3dllok64io32kva",
                locality: "Azad Marg",
                areaName: "C Scheme",
                costForTwo: "₹200 for two",
                cuisines: [
                    "American",
                    "Continental",
                    "Italian-American",
                    "Snacks",
                    "Grill",
                    "Beverages",
                    "Bakery",
                    "Desserts",
                    "Barbecue",
                ],
                avgRating: 4.5,
                parentId: "4660",
                avgRatingString: "4.5",
                totalRatingsString: "10K+",
                sla: {
                    deliveryTime: 26,
                    lastMileTravel: 4.6,
                    serviceability: "SERVICEABLE",
                    slaString: "26 mins",
                    lastMileTravelString: "4.6 km",
                    iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                    nextCloseTime: "2024-01-04 02:00:00",
                    opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                    entityBadges: {
                        imageBased: {},
                        textBased: {},
                        textExtendedBadges: {},
                    },
                },
                aggregatedDiscountInfoV3: {
                    header: "₹75 OFF",
                    subHeader: "ABOVE ₹249",
                    discountTag: "FLAT DEAL",
                },
                differentiatedUi: {
                    displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                    differentiatedUiMediaDetails: {
                        mediaType: "ADS_MEDIA_ENUM_IMAGE",
                        lottie: {},
                        video: {},
                    },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
            },
            analytics: {},
            cta: {
                link: "https://www.swiggy.com/restaurants/burger-farm-azad-marg-c-scheme-jaipur-45977",
                type: "WEBLINK",
            },
        },
    ],
};

export const filteredData = data.restaurants.map((shop) => {
    const { id, name, cuisines, avgRatingString, sla, cloudinaryImageId } = shop.info;
    const { deliveryTime } = sla;
    return { id, name, cuisines, avgRatingString, deliveryTime, cloudinaryImageId };
});
